[package]
name = "test_main"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enoki_exchange_shared = { path = "../enoki_exchange_shared" }
serde = "1.0.137"
serde_json = "1.0.81"